#!/bin/bash
#
# accept eula if set
#
# (c) 2016 nimmis <kjell.havneskold@gmail.com>

if [ ! -z $EULA ] ; then
  
  echo "eula=$EULA" > $SPIGOT_HOME/eula.txt
  chown minecraft $SPIGOT_HOME/eula.txt 

fi 
