#!/bin/bash
# save all env variables (incl ones from docker) for crontab use

printenv | grep -v " " | sed 's/^\(.*\)$/export \1/g' > /minecraft/my_env.sh
chmod 755 /minecraft/my_env.sh
chown minecraft:minecraft /minecraft/my_env.sh
